all: detectionModule digitalRead digitalWrite newAddress reset

detectionModule:detectionModule.cpp ../iarduino_I2C_Relay.cpp
digitalRead:digitalRead.cpp ../iarduino_I2C_Relay.cpp
digitalWrite:digitalWrite.cpp ../iarduino_I2C_Relay.cpp
newAddress:newAddress.cpp ../iarduino_I2C_Relay.cpp
reset:reset.cpp ../iarduino_I2C_Relay.cpp

clean:
	rm -f detectionModule digitalRead digitalWrite newAddress reset
